export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const CHANGE_CENTER = 'CHANGE_CENTER';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const TOGGLE_ROUTE_ON_MAP='TOGGLE_ROUTE_ON_MAP';